server:
  port: 8084

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://gaenari.kr:30036/my_database?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: Ssafy123!@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_1
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

feign:
  member-service:
    url: http://localhost:8081
  inventory-service:
    url: http://localhost:8084
  program-service:
    url: http://localhost:8085
  exercise-record-service:
    url: http://localhost:8086
  challenge-service:
    url: http://localhost:8088